import { createEvent } from "#base";
const frases = [
  "Sabe qual é o cúmulo do desperdício? Jogar conversa fora!",
  "Por que o livro foi ao médico? Porque ele estava com dor de cabeça!",
  "Se a vida te der limões… peça sal e tequila!",
  "Eu ia contar uma piada sobre construção, mas ainda estou trabalhando nela.",
  "Você sabia que o zero disse pro oito? Belo cinto!",
  "Tô lendo um livro sobre gravidade… impossível largar!",
  "Por que o computador foi ao médico? Porque estava com um vírus!",
  "O que o tomate foi fazer no banco? Tirar extrato!",
  "Sabe qual é o animal mais antigo do mundo? A zebra, porque é em preto e branco.",
  "Se correr o bicho pega, se ficar o bicho come. Então vou andar devagar pra ver se confunde!",
  "Eu tentei pegar névoa ontem… mas ‘neblina’.",
  "Por que o pão não entende a piada? Porque ele é francês!",
  "Por que o jacaré tirou o filho da escola? Porque ele réptil de ano!",
  "Fui na academia ontem… pra buscar meu primo!",
  "Por que o lápis se deu mal na prova? Porque ele estava sem ponta!",
  "Qual o contrário de volátil? Vem cá sobrinho!",
  "Sabe qual é o peixe mais curioso? O ‘curiô’!",
  "Meu cachorro aprendeu a dançar… agora ele é um cão-guru!",
  "Por que a planta não responde? Porque ela é muda!",
  "Se eu te contar uma piada de eletricista, vai ser ‘choque’ de risadas!",
  "Por que o relógio foi preso? Porque ele matou o tempo!",
  "Sabe por que a aranha é o animal mais carente? Porque ela vive na teia!",
  "Tentei fazer um chá de sumiço, mas desapareceu!",
  "Por que o pneu se apaixonou? Porque ele ficou careca de amor!",
  "Por que a vaca foi pro espaço? Pra ver o vácuo!",
  "O que o zero falou pro oito? Adorei o cinto!",
  "Eu ia contar uma piada sobre papel, mas é meio rasgada.",
  "Você sabe qual é o cúmulo da velocidade? Tomar café com pressa e acordar antes de dormir.",
  "Sabe qual é o contrário de papelada? Pádevaca!",
  "Por que o fotógrafo foi preso? Porque foi pego revelando segredos!",
  "Sabe o que é um pontinho amarelo na neve? Um urso mijando!",
  "Se a vida te derrubar, finge que foi coreografia!",
  "Qual é o carro que não tem freio? O carroço!",
  "Eu comprei um relógio de cebola… toda vez que olho, choro.",
  "Sabe o que o pintinho falou pro outro? Vem cá, pio!",
  "Meu tio comprou uma balança nova… agora tá pesando as palavras!",
  "Por que o lápis nunca é preso? Porque ele sempre está na linha.",
  "Sabe o que o tijolo disse pro outro? Há um ciumento entre nós!",
  "Sabe o que o vento disse pro fogo? ‘Não se apague comigo!’",
  "Por que o cachorro entrou na igreja? Porque ele era um cão fiel!",
  "Se eu fosse você, eu seria eu também!",
  "Qual o contrário de formidável? Fundetrás!",
  "Por que o pintinho não pode jogar no time? Porque ele só chuta ovo!",
  "O que é um pontinho verde no canto da sala? Um feijão de castigo!",
  "Sabe o que o cavalo foi fazer no orelhão? Passar um trote!",
  "Por que o escorpião não gosta de dividir? Porque ele é muito venenoso!",
  "Você conhece a piada do pônei? Deixa pra lá, é meio pequena.",
  "Por que o elefante não pega fogo? Porque ele já é cinza!",
  "Eu ia contar uma piada sobre pizza, mas é meio massa.",
  "Qual o cúmulo do azar? Ser atropelado por um carro alegórico triste.",
  "Sabe o que o pato falou pra pata? ‘Vem quá!’",
  "Por que o mar não se dá bem com o rio? Porque ele é salgado!",
  "Se a preguiça fosse esporte, eu ganhava por WO.",
  "O que o chão falou pro tapete? ‘Tô coberto de razão!’",
  "Sabe o que o açúcar falou pro café? ‘Você me completa!’",
  "Por que o menino jogou o relógio pela janela? Porque queria ver o tempo voar!",
  "Sabe o que o papel disse pra caneta? ‘Tô escrevendo pra você!’",
  "Se eu contar uma piada de peixe, vai ser profunda.",
  "Por que o esqueleto não briga? Porque ele não tem estômago pra isso!",
  "Sabe o que o pneu falou pro carro? ‘Sem você eu fico rodando em falso!’",
  "O que é um pontinho vermelho no jardim? Um morangotango!",
  "Sabe qual é o doce preferido do átomo? Pé de molécula!",
  "Por que o coelho atravessou a rua? Pra mostrar que não é galinha!",
  "Eu ia contar uma piada de eletricista, mas pode dar curto!",
  "Por que o jacaré não gosta de tirar selfie? Porque ele já é um réptil!",
  "Sabe o que o chinelo falou pro pé? ‘Não me pise!’",
  "O que é um pontinho preto no céu? Uma formiga voadora!",
  "Sabe o que o peixe disse pro outro? Nada, nada!",
  "Por que o computador dorme bem? Porque tem muitos megas de sono!",
  "Sabe qual é o contrário de papelão? Pádevaca!",
  "Por que o vento não vai à escola? Porque já é um ventilado!",
  "Se a vida te der batatas, faz purê!",
  "O que é um pontinho azul no canto? Uma formiguinha triste do Goku!",
  "Sabe qual é o cúmulo da preguiça? Levantar pra dormir!",
  "Por que o queijo não conta piada? Porque pode ralar!",
  "Sabe o que o relógio disse pro calendário? ‘Eu tô cheio de hora!’",
  "Por que a abelha sempre sabe o que está acontecendo? Porque ela é muito bem informada!",
  "Por que o livro de matemática terminou com o de história? Porque ele tinha muitos problemas.",
  "Sabe o que o iogurte foi fazer na academia? Ficar mais consistente!",
  "O que é um pontinho roxo na parede? Uma uva assistindo aula!",
  "Sabe por que o celular foi preso? Porque tocou no assunto errado!",
  "Por que o espelho foi preso? Porque refletiu demais!",
  "Por que o computador foi ao terapeuta? Porque estava cheio de bugs emocionais!",
  "Sabe qual é o peixe mais elegante? O esturjão!",
  "Eu tentei pegar um peixe, mas ele me deu um fora… escamoso!",
  "Sabe o que o fósforo disse pra vela? ‘Tô aceso por você!’",
  "Por que o ovo não contou piada? Porque ele podia se quebrar de rir!",
  "Se o cachorro tivesse GPS, seria um cão-guia atualizado.",
  "Por que o café foi preso? Porque acorda todo mundo!",
  "Sabe o que o trovão disse pro relâmpago? ‘Você me ilumina!’",
  "Por que o sabão foi promovido? Porque fazia tudo limpinho!",
  "Sabe qual é o carro do padeiro? O pão-de-rola!",
  "Por que o professor de música foi preso? Porque foi pego com notas falsas!",
  "Sabe o que o elevador disse pro andar? ‘Subo, mas volto!’",
  "Por que o pintor não foi pra escola? Porque ele já tinha muita tinta no currículo!",
  "Sabe o que o celular disse pro carregador? ‘Você me completa!’",
  "Por que o calendário é popular? Porque tem muitos dias marcados!",
  "Sabe o que o papel disse pra impressora? ‘Você me dá vida!’",
  "Se rir é o melhor remédio, eu sou o farmacêutico!",
  "Sabe por que o peixe não gosta do computador? Porque tem medo da rede!"
];

export default createEvent({
    name: "status",
    event: "ready",
    async run(client) {
        // Status do bot
        let idx = Math.floor(Math.random() * frases.length);
        function setStatus() {
            const frase = frases[idx];
            client.user.setActivity({
                name: frase,
                type: 1, // Streaming
                url: "https://twitch.tv/acipblox" // url obrigatória para ícone roxo
            });
            idx = (idx + 1) % frases.length;
        }
        setStatus();
        setInterval(setStatus, 2 * 60 * 1000); // troca a cada 2 minutos
    }
});